language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: davidcaseria@gmail.com
  api_key:
    secure: IbFCNFQqe0sX2oZ2lRcURijbtIJeVjLOgEkENhnQxtkcSAtMUOQw2NRdOcmYEOvFI5qAUOUXZV7G2JjHIIgws15pX2cbBhUncB6BURIrsPuE8GkoIctA+2RLIxo7Yef3dXU31DRzySdGfN5JyUb7/1F3aFarYtm0Nq6Dy8qQMMw=
  on:
    tags: true
    repo: davidcaseria/StripeFire
    branch: master
